title: Project Portfolio
author: Virgil Aurand
email: virgil@vcoproject.com
description: > # this means to ignore newlines until "baseurl:"
  This is an overview of some of the projects and solutions I've implemented.   
# social links
twitter_username: virgilaurand
github_username:  virgilaurand

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
